INSERT INTO sc_mst."option" (kdoption,nmoption,value1,value2,value3,status,keterangan,input_by,update_by,input_date,update_date,group_option) VALUES
	 ('PKPA:S','PKPA SUPPERIOR','',NULL,NULL,'T','','MIGRATION',NULL,now(),NULL,'PKPA'),
	 ('PKPA:ACCESS','USER PKPA','PST.HRGA',NULL,NULL,'T','','MIGRATION',NULL,now(),NULL,'PKPA'),
	 ('PKPAAHR','SETUP APPROVAL HR','T',NULL,NULL,'T','','MIGRATION',NULL,now(),NULL,'PKPA'),
	 ('PKPACL','SETUP CEK TX CLOSE FINAL SCORE',NULL,NULL,NULL,'T','SETUP CEK INPUTAN HARUS FINAL SAAT CLOSE FINAL SCORE','MIGRATION',NULL,now(),NULL,'PKPA'),
	 ('PKPALE','SETUP LEVEL EXCEPTION','D,E,F,G',NULL,NULL,'T','SETUP PENGECUALIAN LEVEL PENILAIAN KARYAWAN','MIGRATION',NULL,now(),NULL,'PKPA'),
	 ('PKPAQE','SETUP QUESTION EXCEPTION','AS02-05,AS02-06',NULL,NULL,'T','SETUP PENGECUALIAN PERTANYAAN','MIGRATION',NULL,now(),NULL,'PKPA')
ON CONFLICT
    DO NOTHING;