INSERT INTO sc_pk.m_area (branch, idbu, kdarea, description)
select 'SBYNSA', 'AR', kddept, nmdept from sc_mst.departmen
ON CONFLICT
    DO NOTHING ;


INSERT INTO sc_pk.m_aspek (branch,idbu,kdaspek,description) VALUES
	 ('SBYNSA','AR','AS01','DISIPLIN'),
	 ('SBYNSA','AR','AS02','SKILL'),
	 ('SBYNSA','AR','AS03','TANGGUNG JAWAB TERHADAP PEKERJAAN')
ON CONFLICT
    DO NOTHING ;


INSERT INTO sc_pk.m_aspek_kriteria (branch,idbu,kdaspek,kdkriteria,description,fulldescription) VALUES
	 ('SBYNSA','AR','AS01','AS01-01','KEHADIRAN', 'KESANGGUPAN UNTUK BERADA DI TEMPAT KERJA SESUAI DENGAN WAKTU KERJA YANG TELAH DITENTUKAN DAN DAPAT MEMANFAATKAN WAKTU KERJA DENGAN SEBAIK - BAIKNYA'),
	 ('SBYNSA','AR','AS01','AS01-02','KETAATAN PADA PERATURAN YANG BERLAKU','KESADARAN DAN KESEDIAAN UNTUK MENGIKUTI DAN MELAKSANAKAN PERATURAN PERUSAHAAN DAN ATURAN-ATURAN YANG TELAH DITETAPKAN PERUSAHAAN'),
	 ('SBYNSA','AR','AS01','AS01-03','KEPEDULIAN PADA PERALATANDAN KEBERSIHAN TEMPAT KERJA','KESADARAN DAN KEMAUAN UNTUK MEMELIHARA PERALATAN KERJA DAN KEBERSIHAN TEMPAT KERJA YANG DITUNJUKKAN DENGAN PERBUATAN NYATA'),
	 ('SBYNSA','AR','AS01','AS01-04','SEMANGAT KERJA','KEMAUAN DAN MOTIVASI POSITIF UNTUK BEKERJA DENGAN SEBAIK-BAIKNYA '),
	 ('SBYNSA','AR','AS01','AS01-05','PEMAKAIAN ALAT PELINDUNG DIRI (APD)','KESADARAN AKAN PENTINGNYA KESELAMATAN DAN KESEHATAN KERJA DENGAN MEMAKAI ALAT PELINDUNG DIRI (APD) SECARA LENGKAP DAN TEPAT'),
	 ('SBYNSA','AR','AS02','AS02-01','PENGUASAAN TERHADAP PEKERJAAN','KEMAMPUAN MELAKSANAKAN TUGAS PEKERJAANNYA DAN DAPAT MENGATASI PERMASALAHAN YANG TIMBUL BERKAITAN DENGAN PEKERJAANNYA'),
	 ('SBYNSA','AR','AS02','AS02-02','INISIATIF DAN KREATIVITAS','KEMAMPUAN UNTUK MENGAMBIL LANGKAH-LANGKAH POSITIF DALAM USAHA UNTUK MEMPERBAIKI SISTEM KERJA DI DALAM MENGATASI MASALAH TANPA PETUNJUK ATASAN'),
	 ('SBYNSA','AR','AS02','AS02-03','KERJASAMA','KEMAMPUAN DALAM MEMBINA HUBUNGAN KERJA SAMA DENGAN REKAN KERJA, ATASAN MAUPUN BAWAHAN DALAM MENCAPAI TUJUAN PERUSAHAAN'),
	 ('SBYNSA','AR','AS02','AS02-04','KOMUNIKASI','KEMAMPUAN MENYAMPAIKAN MAUPUN MENDENGARKAN PENDAPAT/USUL/IDE DAN SEMUA PERMASALAHAN YANG BERHUBUNGAN DENGAN PEKERJAAN  DALAM RANGKA MENCAPAI TUJUAN PERUSAHAAN'),
	 ('SBYNSA','AR','AS02','AS02-05','KEPEMIMPIAN','KEMAMPUAN UNTUK MERENCANAKAN/MENGKOORDINIR/MENGARAHKAN/MENGAWASI ANAK BUAH DALAM MELAKUKAN TUGAS ATAU PEKERJAAN'),
	 ('SBYNSA','AR','AS02','AS02-06','PENGAMBILAN KEPUTUSAN','KEMAMPUAN UNTUK MELIHAT PERMASALAHAN, MENCARI SOLUSI DAN MEMBUAT KEPUTUSAN YANG TEPAT JIKA BERHADAPAN DENGAN SUATU MASALAH'),
	 ('SBYNSA','AR','AS03','AS03-01','MENGIKUTI PROSEDUR KERJA YANG TELAH DITETAPKAN','KESADARAN DAN KESEDIAAN UNTUK BEKERJA SESUAI DENGAN STANDAR DAN PROSEDUR YANG TELAH DITETAPKAN UNTUK MENCAPAI EFEKTIVITAS DAN EFISIENSI KERJA YANG OPTIMAL'),
	 ('SBYNSA','AR','AS03','AS03-02','BERTANGGUNG JAWAB PADA KUALITAS HASIL PEKERJAAN','KESANGGUPAN UNTUK MELAKSANAKAN TUGAS PEKERJAAN SESUAI TARGET BAIK SECARA KUALITAS MAUPUN KUANTITAS DAN KESEDIAAN UNTUK MENANGGUNG RISIKO DARI PEKERJAAN YANG DILAKUKAN')
ON CONFLICT
    DO NOTHING ;


INSERT INTO sc_pk.m_bobot (branch,idbu,kdcategory,kdvalue,description,value1,value2,value3,value4,value5,cgroup,inputdate,inputby,updatedate,updateby,status,chold) VALUES
	 ('SBYNSA','AR','PA','SK','SANGAT KURANG','1','0',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','PA','K','KURANG','2','1.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','PA','C','CUKUP','3','2.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','PA','B','BAGUS','4','3.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','PA','SB','SANGAT BAGUS','5','4.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KPI','SK','SANGAT KURANG','1','0',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KPI','K','KURANG','2','1.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KPI','C','CUKUP','3','2.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KPI','B','BAGUS','4','3.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KPI','SB','SANGAT BAIK','5','4.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KONDITE','SK','SANGAT KURANG','21.5','','1','','','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KONDITE','K','KURANG','22.99','21.51','2','1.01','','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KONDITE','C','CUKUP','23.99','23','3','2.01','','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KONDITE','B','BAGUS','24.99','24','4','3.01','','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KONDITE','SB','SANGAT BAGUS','2','25','5 ','4.01','','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','KONDITE','KUOTA','KUOTA','2','',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FSC2','PA','FINAL','1','',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FSC2','KONDITE','FINAL','2','',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FSC2','KPI','FINAL','7','',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FSC1','PA','FINAL','1','',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FSC1','KONDITE','FINAL','2','',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FSC1','KPI','FINAL','7','',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FINAL','SK','SANGAT KURANG','1','0',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FINAL','K','KURANG','2','1.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FINAL','C','CUKUP','3','2.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FINAL','B','BAGUS','4','3.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL),
	 ('SBYNSA','AR','FINAL','SB','SANGAT BAGUS','5','4.01',NULL,NULL,'','PA',now(),'MIGRATION',NULL,NULL,NULL,NULL)
ON CONFLICT
    DO NOTHING ;


INSERT INTO sc_pk.m_formula_condite (branch,idbu,kdrumus,objectcode,objectname,value1,value2,cgroup) VALUES
	 ('SBYNSA','AR','MRPA001','IP','IJIN PRIBADI','-1.00','4.00','PA'),
	 ('SBYNSA','AR','MRPA002','SD','SURAT DOKTER','-0.50','2.00','PA'),
	 ('SBYNSA','AR','MRPA003','AL','ALPHA','-3','12.00','PA'),
	 ('SBYNSA','AR','MRPA004','ITL','TERLAMBAT','-0.50','2.00','PA'),
	 ('SBYNSA','AR','MRPA005','IPA','PULANG AWAL','-0.50','2.00','PA'),
	 ('SBYNSA','AR','MRPA006','SP1','SP 1','-5.00','20.00','PA'),
	 ('SBYNSA','AR','MRPA007','SP2','SP 2','-6.00','24.00','PA'),
	 ('SBYNSA','AR','MRPA008','SP3','SP 3','-7.00','28.00','PA'),
	 ('SBYNSA','AR','MRPA009','CT','CUTI','0','0','PA'),
	 ('SBYNSA','AR','MRPA010','IK','IJIN KHUSUS','0','0','PA'),
	 ('SBYNSA','AR','MRPA011','TL','TERLAMBAT','-1.50','6.00','PA')
ON CONFLICT
    DO NOTHING ;


INSERT INTO sc_pk.m_pk_option (branch,idbu,kdpk,condition1,description) VALUES
	 ('SBYNSA','AR','PA','LINK','PERFORMA APPRAISAL'),
	 ('SBYNSA','AR','KD','LINK','KONDITE'),
	 ('SBYNSA','AR','KPI','LINK','KEY PERFORMANCE INDICATOR')
ON CONFLICT
    DO NOTHING ;

INSERT INTO sc_pk.m_aspek_question (branch,idbu,kdkriteria,questionid,point,description) VALUES
	 ('SBYNSA','AR','AS01-01','AS01-01-01',1,'TIDAK BERADA DI TEMPAT KERJA TANPA ALASAN YANG JELAS/BISA DIPERTANGGUNGJAWABKAN (LEBIH DARI 15 MENIT) LEBIH DARI 3 KALI ATAU TERLAMBAT DATANG KE TEMPAT KERJA LEBIH DARI 3 KALI SELAMA PERIODE PENILAIAN.'),
	 ('SBYNSA','AR','AS01-01','AS01-01-02',2,'TIDAK BERADA DI TEMPAT KERJA TANPA ALASAN YANG JELAS/BISA DIPERTANGGUNGJAWABKAN (LEBIH DARI 15 MENIT) LEBIG DARI 2 KALI ATAU TERLAMBAT DATANG KE TEMPAT KERJA LEBIH DARI 2 KALI SELAMA PERIODE PENILAIAN.'),
	 ('SBYNSA','AR','AS01-01','AS01-01-03',3,'PERNAH MENINGGALKAN TEMPAT KERJA TANPA ALASAN YANG JELAS/BISA DIPERTANGGUNGJAWABKAN (LEBIH DARI 15 MENIT) ATAU DATANG TERLAMBAT KE TEMPAT KERJA SELAMA PERIODE PENILAIAN.'),
	 ('SBYNSA','AR','AS01-01','AS01-01-04',4,'BERADA DI TEMPAT KERJA TEPAT WAKTU DAN SIAP MELAKSANAKAN PEKERJAAN/TUGAS YANG DIBERIKAN.'),
	 ('SBYNSA','AR','AS01-01','AS01-01-05',5,'SELALU TEPAT WAKTU DAN MAMPU MEMANFAATKAN WAKTU KERJA DENGAN OPTIMAL (PRODUKTIF) SERTA BISA MENJADI PANUTAN BAGI KARYAWAN YANG LAIN.'),
	 ('SBYNSA','AR','AS01-02','AS01-02-01',1,'MELANGGAR PERATURAN PERUSAHAAN LEBIH DARI 2 KALI DAN MENDAPAT SURAT PERINGATAN.'),
	 ('SBYNSA','AR','AS01-02','AS01-02-02',2,'PERNAH MELANGGAR PERATURAN PERUSAHAAN DAN MENDAPAT SURAT PERINGATAN.'),
	 ('SBYNSA','AR','AS01-02','AS01-02-03',3,'PERNAH MELANGGAR PERATURAN PERUSAHAAN DAN MENDAPAT TEGURAN LISAN.'),
	 ('SBYNSA','AR','AS01-02','AS01-02-04',4,'TIDAK PERNAH MELAKUKAN PELANGGARAN PERATURAN PERUSAHAAN.'),
	 ('SBYNSA','AR','AS01-02','AS01-02-05',5,'SECARA AKTIF MENCIPTAKAN LINGKUNGAN KERJA YANG KONDUSIF DAN MENJADI CONTOH POSITIF BAGI KARYAWAN YANG LAIN.'),
	 ('SBYNSA','AR','AS01-03','AS01-03-01',1,'MELAKUKAN PERAWATAN PERALATAN KERJA DAN ATAU MEMBERSIHKAN TEMPAT KERJA BILA DIINGATKAN ATAU BILA ADA YANG MENGAWASI.'),
	 ('SBYNSA','AR','AS01-03','AS01-03-02',2,'MEMPUNYAI KESADARAN UNTUK MELAKUKAN PERAWATAN PERALATAN KERJA DAN ATAU PEDULI PADA KEBERSIHAN TEMPAT KERJA.'),
	 ('SBYNSA','AR','AS01-03','AS01-03-03',3,'SELALU MERAWAT PERALATAN KERJA DAN MENJAGA KEBERSIHAN TEMPAT KERJA.'),
	 ('SBYNSA','AR','AS01-03','AS01-03-04',4,'MEMBERIKAN MASUKAN/SARAN/PERBAIKAN SISTEM PERAWATAN PERALATAN KERJA ATAU UNTUK MENJAGA KEBERSIHAN TEMPAT KERJA YANG LEBIH BAIK.'),
	 ('SBYNSA','AR','AS01-03','AS01-03-05',5,'MENGAJAK/MENGINGATKAN KARYAWAN LAIN UNTUK MELAKUKAN PERAWATAN PERALATAN KERJA DAN ATAU MENJAGA KEBERSIHAN TEMPAT KERJA.'),
	 ('SBYNSA','AR','AS01-04','AS01-04-01',1,'BEKERJA ASAL-ASALAN, HANYA UNTUK MEMENUHI JAM KERJA.'),
	 ('SBYNSA','AR','AS01-04','AS01-04-02',2,'BEKERJA HANYA SEKEDAR MENJALANKAN TUGAS DAN UNTUK MEMENUHI JAM KERJA.'),
	 ('SBYNSA','AR','AS01-04','AS01-04-03',3,'BEKERJA DENGAN SUNGGUH-SUNGGUH MESKIPUN HASILNYA MASIH STANDAR.'),
	 ('SBYNSA','AR','AS01-04','AS01-04-04',4,'BEKERJA DENGAN SUNGGUH-SUNGGUH DAN PENUH KONSENTRASI SEHINGGA HASILNYA SESUAI TARGET.'),
	 ('SBYNSA','AR','AS01-04','AS01-04-05',5,'MAMPU MEMBERIKAN MOTIVASI BAGI KARYAWAN LAIN UNTUK BEKERJA DENGAN SEBAIK-BAIKNYA.'),
	 ('SBYNSA','AR','AS01-05','AS01-05-01',1,'TIDAK MENGGUNAKAN ALAT PELINDUNG DIRI (APD) SECARA LENGKAP.'),
	 ('SBYNSA','AR','AS01-05','AS01-05-02',2,'MENGGUNAKAN ALAT PELINDUNG DIRI (APD) SECARA LENGKAP APABILA DIINGATKAN/DIAWASI.'),
	 ('SBYNSA','AR','AS01-05','AS01-05-03',3,'SELALU MENGGUNAKAN ALAT PELINDUNG DIRI (APD) SECARA LENGKAP DAN TEPAT.'),
	 ('SBYNSA','AR','AS01-05','AS01-05-04',4,'MEMBERIKAN MASUKAN/PERBAIKAN BAGI SISTEM KESELAMATAN DIRI DI TEMPAT KERJA YANG LEBIH BAIK.'),
	 ('SBYNSA','AR','AS01-05','AS01-05-05',5,'MAMPU MENJADI TELADAN BAGI KARYAWAN LAIN DALAM HAL PENGGUNAAN ALAT PELINDUNG DIRI (APD) SECARA LENGKAP DAN TEPAT.'),
	 ('SBYNSA','AR','AS02-01','AS02-01-01',1,'MENGUASAI PROSES PEKERJAAN STANDAR TETAPI MASIH MEMERLUKAN PENGAWASAN/BIMBINGAN DARI ATASAN.'),
	 ('SBYNSA','AR','AS02-01','AS02-01-02',2,'MENGERTI TUGAS-TUGASNYA DAN PROSES-PROSES PEKERJAAN STANDAR BERJALAN DENGAN BAIK.'),
	 ('SBYNSA','AR','AS02-01','AS02-01-03',3,'MENGUASAI PROSES-PROSES PEKERJAAN STANDAR DAN MAMPU MENGATASI MASALAH SEDERHANA YANG TERJADI.'),
	 ('SBYNSA','AR','AS02-01','AS02-01-04',4,'MENGUASAI SEMUA PROSES-PROSES PEKERJAAN DI BAGIANNYA DAN MAMPU MENGATASI MASALAH YANG KOMPLEKS YANG BERKAITAN DENGAN PEKERJAANNYA'),
	 ('SBYNSA','AR','AS02-01','AS02-01-05',5,'MAMPU MEMBERIKAN PELATIHAN/BIMBINGAN BAGI KARYAWAN LAIN.'),
	 ('SBYNSA','AR','AS02-02','AS02-02-01',1,'PASIF (MENUNGGU PERINTAH)/HARUS SELALU DIDORONG UNTUK MENYELESAIKAN PEKERJAAN.'),
	 ('SBYNSA','AR','AS02-02','AS02-02-02',2,'PERLU DORONGAN UNTUK MENCAPAI HASIL RATA-RATA.'),
	 ('SBYNSA','AR','AS02-02','AS02-02-03',3,'TIDAK PERLU DORONGAN LAGI, BEKERJA SESUAI DENGAN APA YANG DIGARISKAN (SYSTEM DAN PROSEDUR YANG BERLAKU).'),
	 ('SBYNSA','AR','AS02-02','AS02-02-04',4,'BERUSAHA MEMULAI SUATU PEKERJAAN ATAS PRAKARSA SENDIRI & CUKUP KREATIF KEARAH YANG POSITIF/PRODUKTIF.'),
	 ('SBYNSA','AR','AS02-02','AS02-02-05',5,'INISIATIF & KREATIVITAS SANGAT MENONJOL, BAHKAN DAPAT MEMBERIKAN DORONGAN & SUMBANGAN IDE BAGI PENGEMBANGAN YANG POSITIF/PRODUKTIF.'),
	 ('SBYNSA','AR','AS02-03','AS02-03-01',1,'TIDAK DAPAT BEKERJA SAMA DENGAN TEMAN/ATASAN & SERINGKALI MENYEBABKAN BENTROKAN.'),
	 ('SBYNSA','AR','AS02-03','AS02-03-02',2,'DALAM KERJASAMA KELOMPOK, SIKAPNYA ACUH TAK ACUH (TIDAK PEDULI) TERHADAP TUGAS KELOMPOK ATAU CENDERUNG MENONJOLKAN DIRI.'),
	 ('SBYNSA','AR','AS02-03','AS02-03-03',3,'MAMPU KERJASAMA DENGAN REKAN KERJA ATAU ATASAN DAN MENUNJUKKAN HUBUNGAN KERJA YANG MENYENANGKAN UNTUK MENCAPAI TUJUAN PERUSAHAAN.'),
	 ('SBYNSA','AR','AS02-03','AS02-03-04',4,'GIAT MELIBATKAN DIRI DALAM TIM KERJA UNTUK MENCAPAI TUJUAN PERUSAHAAN, KOMPAK.'),
	 ('SBYNSA','AR','AS02-03','AS02-03-05',5,'LEBIH MENGUTAMAKAN KEPENTINGAN TIM KERJA DARIPADA KEPENTINGAN PRIBADI DALAM MENCAPAI TUJUAN PERUSAHAAN.'),
	 ('SBYNSA','AR','AS02-04','AS02-04-01',1,'SIFAT KOMUNIKASI SEARAH (MENUNGGU INSTRUKSI DARI PIMPINAN), INSTRUKSI/TUGAS DARI PIMPINAN SEBAGAI BEBAN.'),
	 ('SBYNSA','AR','AS02-04','AS02-04-02',2,'SIFAT KOMUNIKASI 2 ARAH TETAPI PASIF, INSTRUKSI PIMPINAN DILAKSANAKAN DENGAN TANGGUNG JAWAB.'),
	 ('SBYNSA','AR','AS02-04','AS02-04-03',3,'SIFAT KOMUNIKASI 2 ARAH SECARA AKTIF, INSTRUKSI PIMPINAN DILAKSANAKAN DENGAN TANGGUNG JAWAB DAN MEMBERIKAN LAPORAN PELAKSANAAN TUGAS.'),
	 ('SBYNSA','AR','AS02-04','AS02-04-04',4,'SIFAT KOMUNIKASI 2 ARAH SECARA AKTIF, KOORDINASI UNTUK ANTISIPASI RESIKO TUGAS DENGAN MEMBERIKAN LAPORAN PELAKSANAAN TUGAS YANG EFISIEN.'),
	 ('SBYNSA','AR','AS02-04','AS02-04-05',5,'SIFAT KOMUNIKASI 2 ARAH SECARA AKTIF, KOORDINASI UNTUK ANTISIPASI RESIKO TUGAS DENGAN MEMBERIKAN LAPORAN PELAKSANAAN TUGAS DAN PETANGGUNGJAWABAN SECARA INTENSIF.'),
	 ('SBYNSA','AR','AS02-05','AS02-05-01',1,'TIDAK DAPAT MENGATUR ANAK BUAH DAN KURANG MAMPU BERKOORDINASI DENGAN BAGIAN LAIN.'),
	 ('SBYNSA','AR','AS02-05','AS02-05-02',2,'DAPAT MENGKOORDINIR ANAK BUAH TETAPI BERSIKAP KURANG TEGAS TERHADAP ANAK BUAH.'),
	 ('SBYNSA','AR','AS02-05','AS02-05-03',3,'DAPAT MENGKOORDINIR ANAK BUAH DAN BERSIKAP TEGAS TERHADAP ANAK BUAH SERTA MAMPU BERKOORDINASI DENGAN BAGIAN LAIN.'),
	 ('SBYNSA','AR','AS02-05','AS02-05-04',4,'KOORDINASI, PENGARAHAN SERTA PENGAWASAN DILAKUKAN DENGAN INTENS SEHINGGA ANAK BUAH DAPAT TERKONTROL DENGAN BAIK.'),
	 ('SBYNSA','AR','AS02-05','AS02-05-05',5,'SELALU KONSISTEN BERSIKAP DAN BERTINDAK DALAM MENGARAHKAN/MENGAWASI ANAK BUAH SEHINGGA MAMPU MENJADI TELADAN BAGI ANAK BUAHNYA DALAM MELAKSANAKAN TUGAS/PEKERJAAN UNTUK MENCAPAI TARGET BERSAMA.'),
	 ('SBYNSA','AR','AS02-06','AS02-06-01',1,'CENDERUNG PASIF DAN MENGHINDAR JIKA ADA MASALAH BAIK MASALAH BESAR ATAUPUN KECIL.'),
	 ('SBYNSA','AR','AS02-06','AS02-06-02',2,'MELIMPAHKAN SOLUSI & KEPUTUSAN KEPADA PIMPINAN YANG LEBIH TINGGI DAN BERHARAP PIMPINAN YANG MEMUTUSKAN.'),
	 ('SBYNSA','AR','AS02-06','AS02-06-03',3,'MAMPU MEMBUAT KEPUTUSAN UNTUK MASALAH YANG BERSIFAT KECIL TETAPI BELUM MAMPU MEMBUAT KEPUTUSAN YANG BERDAMPAK BESAR BAGI SISTEM KERJA DI LINGKUNGANNYA.'),
	 ('SBYNSA','AR','AS02-06','AS02-06-04',4,'SUDAH MAMPU SECARA JELI MELIHAT PERMASALAHAN, MENCARI SOLUSI DAN MEMBUAT KEPUTUSAN YANG TEPAT UNTUK SETIAP KONDISI YANG TERJADI.'),
	 ('SBYNSA','AR','AS02-06','AS02-06-05',5,'MAMPU SECARA JELI MELIHAT SUATU PERMASALAHAN, MENCARI ALTERNATIF SOLUSI DAN MEMBUAT KEPUTUSAN YANG EFEKTIF DAN EFISIEN UNTUK SETIAP KONDISI DAN SELALU MEMIKIRKAN LANGKAH ANTISIPATIF.'),
	 ('SBYNSA','AR','AS03-01','AS03-01-01',1,'BEKERJA MELALAIKAN PROSEDUR STANDAR YANG DITETAPKAN, SERINGKALI MELAKUKAN KESALAHAN SEHINGGA MENDAPATKAN TEGURAN/PERINGATAN DARI PIMPINAN.'),
	 ('SBYNSA','AR','AS03-01','AS03-01-02',2,'BEKERJA SESUAI DENGAN PROSEDUR STANDAR, TETAPI MASIH MELAKUKAN KESALAHAN KERJA ATAU KETIDAKSESUAI DALAM KERJA.'),
	 ('SBYNSA','AR','AS03-01','AS03-01-03',3,'BEKERJA MENGIKUTI PROSEDUR STANDAR, TIDAK PERNAH MELAKUKAN KESALAHAN ATAU KETIDAKSESUAIN DALAM KERJA.'),
	 ('SBYNSA','AR','AS03-01','AS03-01-04',4,'BEKERJA MENGIKUTI PROSEDUR STANDAR, TIDAK PERNAH MELAKUKAN KESALAHAN ATAU KETIDAKSESUAIAN DALAM KERJA DAN PERNAH MENGAJUKAN USUL/IDE UNTUK PERBAIKAN PROSEDUR KERJA YANG LEBIH EFEKTIF DAN EFISIEN.'),
	 ('SBYNSA','AR','AS03-01','AS03-01-05',5,'BEKERJA MENGIKUTI PROSEDUR STANDAR, TIDAK PERNAH MELAKUKAN KESALAHAN ATAU KETIDAKSESUAIN DALAM KERJA DAN BERPERAN AKTIF DALAM PERBAIKAN PROSEDUR KERJA YANG LEBIH EFEKTIF DAN EFISIEN.'),
	 ('SBYNSA','AR','AS03-02','AS03-02-01',1,'KURANG TELITI PADA PEKERJAAN SEHINGGA MENGHASILKAN KUALITAS DAN KUANTITAS YANG TIDAK SESUAI DENGAN TARGET YANG DITETAPKAN.'),
	 ('SBYNSA','AR','AS03-02','AS03-02-02',2,'MAMPU MENYELESAIKAN TUGAS DENGAN KUALITAS DAN KUANTITAS SESUAI DENGAN TARGET YANG DITETAPKAN.'),
	 ('SBYNSA','AR','AS03-02','AS03-02-03',3,'MAMPU MENYELESAIKAN TUGAS DENGAN KUALITAS DAN KUANTITAS HASIL PEKERJAAN MELEBIHI TARGET YANG DITETAPKAN DAN  BERSEDIA MELAKUKAN TINDAKAN KOREKSI/PERBAIKAN TERHADAP TUGAS YANG DITANGANI.'),
	 ('SBYNSA','AR','AS03-02','AS03-02-04',4,'TIDAK PERNAH MEMBUAT KESALAHAN DALAM MELAKSANAKAN TUGAS/PEKERJAAN DENGAN KUALITAS DAN KUANTITAS HASIL PEKERJAAN YANG MELEBIHI TARGET YANG DITETAPKAN, BAHKAN MAMPU MEMBERIKAN MASUKAN UNTUK PENINGKATAN KUALITAS PEKERJAAN.'),
	 ('SBYNSA','AR','AS03-02','AS03-02-05',5,'MEMPUNYAI KEMAMPUAN MELATIH KARYAWAN LAIN UNTUK MENINGKATKAN KUALITAS DAN KUANTITAS PEKERJAAN.')
ON CONFLICT
    DO NOTHING ;
	
