DO
$$
BEGIN
    IF NOT EXISTS (SELECT column_name FROM information_schema.columns WHERE table_schema = 'sc_trx' AND table_name = 'pomst' ) THEN
        create table sc_trx.pomst (
            branch char (6)  not null ,
            pono char (12)  not null ,
            podate timestamp not null ,
            operator char (8)  not null ,
            postatus char (1)  not null ,
            potipe char (15)  not null ,
            employee char (8)  null ,
            shiptype char (12)  null ,
            shipterm char (6)  null ,
            shipdate timestamp null ,
            itempo numeric(4, 0) null ,
            itemappreq numeric(4, 0) null ,
            itemappved numeric(4, 0) null ,
            itemappdelv numeric(4, 0) null ,
            itempodelv numeric(4, 0) not null ,
            itempodel numeric(4, 0) null ,
            agepo timestamp null ,
            suppcode char (6)  not null ,
            custcode char (6)  null ,
            shipto char (2)  not null ,
            totalvol numeric(12, 2) null ,
            ttlbrutto money not null ,
            ttldisc money null ,
            ttlnetto money not null ,
            ttldpp money not null ,
            ttlppn money not null ,
            approvedby1 varchar (8)  null ,
            approvedby2 varchar (8)  null ,
            flagprint char (1)  null ,
            note text  null ,
            ppn numeric(4, 2) null ,
            idbu char (1)  null ,
            ordertipe char (2)  null ,
            payto char (2)  null ,
            taxref char (2)  null ,
            oappn char (3)  null ,
            oaxppn numeric(4, 2) not null ,
            oattlbrutto money not null ,
            oattlnetto money not null ,
            oattldpp money not null ,
            oattlppn money not null ,
            printed numeric(4, 0) null ,
            inputby char (8)  null ,
            inputdate timestamp null ,
            updateby char (8)  null ,
            updatedate timestamp null ,
            ponotemp char (12)  null ,
            cancelby char (8)  null ,
            canceldate timestamp null ,
            hangusby char (8)  null ,
            hangusdate timestamp null ,
            constraint pomst_pkey primary key (branch,pono)
        );
    END IF;
END
$$
