CREATE TABLE sc_his.perawatanspk_tambahan (
	nodok bpchar(12) NOT NULL,
	nodokref bpchar(20) NULL,
	descbarang bpchar(30) NULL,
	kdgroup bpchar(50) NULL,
	kdsubgroup bpchar(50) NULL,
	stockcode bpchar(50) NULL,
	kdbengkel bpchar(20) NULL,
	kdsubbengkel bpchar(20) NULL,
	upbengkel bpchar(20) NULL,
	jnsperawatan bpchar(20) NULL,
	jnsperawatanref bpchar(20) NULL,
	tgldok timestamp NULL,
	tglawal date NULL,
	tglakhir date NULL,
	km_awal numeric NULL,
	km_akhir numeric NULL,
	ttlservis numeric(18, 2) NULL,
	ttldiskon numeric(18, 2) NULL,
	ttldpp numeric(18, 2) NULL,
	ttlppn numeric(18, 2) NULL,
	ttlppnbm numeric(18, 2) NULL,
	ttlnetto numeric(18, 2) NULL,
	typeservis bpchar(20) NULL,
	keterangan text NULL,
	status bpchar(6) NULL,
	inputdate timestamp NULL,
	inputby bpchar(20) NULL,
	updatedate timestamp NULL,
	updateby bpchar(20) NULL,
	nodoktmp bpchar(20) NULL,
	laporanpk text NULL,
	laporanpsp text NULL,
	laporanksp text NULL,
	id serial
);