CREATE OR REPLACE VIEW sc_trx.po_mst_view
AS SELECT x.branch,
    x.nodok,
    x.nodokref,
    x.loccode,
    x.podate,
    x.kdgroupsupplier,
    x.kdsupplier,
    x.kdsubsupplier,
    x.kdcabangsupplier,
    x.pkp,
    x.ttlbrutto,
    x.ttldiskon,
    x.ttldpp,
    x.ttlppn,
    x.ttlnetto,
    x.payterm,
    x.keterangan,
    x.inputdate,
    x.inputby,
    x.updatedate,
    x.updateby,
    x.approvaldate,
    x.approvalby,
    x.hangusdate,
    x.hangusby,
    x.canceldate,
    x.cancelby,
    x.nodoktmp,
    x.status,
    x.nmsupplier,
    x.nmsubsupplier,
    x.addsupplier,
    x.kdcabang,
    x.phone1,
    x.phone2,
    x.fax,
    x.email,
    x.ownsupplier,
    x.ketstatus,
    x.nmbarang,
    x.locaname,
    x.itemtype,
    x.nik,
    x.nik_atasan,
    x.nik_atasan2 
   FROM ( SELECT a.branch,
            a.nodok,
            a.nodokref,
            a.loccode,
            a.podate,
            a.kdgroupsupplier,
            a.kdsupplier,
            a.kdsubsupplier,
            a.kdcabangsupplier,
            a.pkp,
            COALESCE(a.disc1, 18::numeric, 2::numeric) AS disc1,
            COALESCE(a.disc2, 18::numeric, 2::numeric) AS disc2,
            COALESCE(a.disc3, 18::numeric, 2::numeric) AS disc3,
            COALESCE(a.disc4, 18::numeric, 2::numeric) AS disc4,
            a.exppn,
            COALESCE(a.ttlbrutto, 0::numeric) AS ttlbrutto,
            COALESCE(a.ttldiskon, 0::numeric) AS ttldiskon,
            COALESCE(a.ttldpp, 0::numeric) AS ttldpp,
            COALESCE(a.ttlppn, 0::numeric) AS ttlppn,
            COALESCE(a.ttlnetto, 0::numeric) AS ttlnetto,
            COALESCE(a.payterm, 0::numeric) AS payterm,
            a.keterangan,
            a.inputdate,
            a.inputby,
            a.updatedate,
            a.updateby,
            a.approvaldate,
            a.approvalby,
            a.hangusdate,
            a.hangusby,
            a.canceldate,
            a.cancelby,
            a.nodoktmp,
            a.status,
            c.nmsupplier,
            b.nmsubsupplier,
            b.addsupplier,
            b.kdcabang,
            b.phone1,
            b.phone2,
            b.fax,
            b.email,
            b.ownsupplier,
            d.uraian AS ketstatus,
            e1.nmbarang,
            e2.locaname,
            a.itemtype,
            trim(sm.nik) as nik,
            trim(k.nik_atasan) as nik_atasan,
            trim(k.nik_atasan2) as nik_atasan2
           FROM sc_trx.po_mst a
             LEFT JOIN sc_mst.msubsupplier b ON a.kdsupplier = b.kdsupplier AND a.kdsubsupplier = b.kdsubsupplier
             LEFT JOIN sc_mst.msupplier c ON a.kdgroupsupplier = c.kdgroup AND a.kdsupplier = c.kdsupplier
             LEFT JOIN sc_mst.trxtype d ON a.status = d.kdtrx AND d.jenistrx::text = 'POATK'::text
             LEFT JOIN ( SELECT a_1.branch,
                    a_1.nodok,
                    a_1.stockcode,
                    b_1.nmbarang
                   FROM ( SELECT po_dtl.branch,
                            po_dtl.nodok,
                            min(po_dtl.stockcode) AS stockcode
                           FROM sc_trx.po_dtl
                          GROUP BY po_dtl.branch, po_dtl.nodok) a_1
                     LEFT JOIN sc_mst.mbarang b_1 ON a_1.stockcode = b_1.nodok) e1 ON a.branch = e1.branch AND a.nodok = e1.nodok
             LEFT JOIN sc_mst.mgudang e2 ON a.loccode = e2.loccode::bpchar
             left join sc_trx.sppb_mst sm on a.nodokref = sm.nodok
             left join sc_mst.karyawan k on sm.nik = k.nik) x
  WHERE x.nodok IS NOT NULL
  ORDER BY x.nodok DESC, x.podate DESC;