INSERT INTO sc_mst."option" 
	(kdoption,nmoption,value1,value2,value3,status,keterangan,input_by,update_by,input_date,update_date,group_option) 
VALUES
	 ('WA-BASE-URL:SBYNSA','BASE URL WHATSAPP NUSA','https://192.168.6.29:8888/',NULL,NULL,'T','BASE URL WHATSAPP NUSA','DK','',NOW(),NOW(),'WA'),
	 ('WA-USER:SBYNSA','USER WHATSAPP NUSA','root',NULL,NULL,'T','USER WHATSAPP NUSA','DK','',NOW(),NOW(),'WA'),
	 ('WA-PASSWORD:SBYNSA','PASSWORD WHATSAPP NUSA','#Admin#',NULL,NULL,'T','PASSWORD WHATSAPP NUSA','DK','',NOW(),NOW(),'WA'),
	 ('WA-SEND-LIMIT:SBYNSA','LIMIT KIRIM WA NUSA','5',NULL,NULL,'T','LIMIT KIRIM WA NUSA','DK',NULL,NOW(),NOW(),'WA'),
	 ('WA-SESSION:SBYNSA','WA SESSION NUSA','sDnp7MqkinhT4Gj39c9QHPXBh',NULL,NULL,'T','WA SESSION NUSA','DK',NULL,NOW(),NOW(),'WA')
ON CONFLICT 
DO NOTHING;