CREATE TABLE sc_trx.po_pembayaran (
	nodok bpchar(20) NOT NULL,
	nodokref bpchar(20) NOT NULL,
	id INT NOT NULL,
	tgl date NULL,
	payment_type VARCHAR NULL,
	keterangan bpchar(100) NULL,
	nbrutto numeric(18, 2) NULL,
	ndiskon numeric(18, 2) NULL,
	ndpp numeric(18, 2) NULL,
	nppn numeric(18, 2) NULL,
	nnetto numeric(18, 2) NULL,	
	inputdate timestamp NULL,
	inputby bpchar(20) NULL,
	updatedate timestamp NULL,
	updateby varchar(20) NULL,
	status bpchar(12) NULL,
	nodoktmp bpchar(20) NOT NULL,
	CONSTRAINT po_pembayaran_trx_pkey PRIMARY KEY (nodok, nodokref, id)
);