CREATE TABLE sc_tmp.po_mst_lampiran (
	nodok bpchar(20) NOT NULL,
	nodokref bpchar(20) NOT NULL,
	id serial,
	idfaktur bpchar(100) NULL,
	tgl date NULL,
	keterangan bpchar(100) NULL,
	nbrutto numeric(18, 2) NULL,
	ndiskon numeric(18, 2) NULL,
	ndpp numeric(18, 2) NULL,
	nppn numeric(18, 2) NULL,
	nnetto numeric(18, 2) NULL,
	jnspo bpchar(20) NULL,
	inputdate timestamp NULL,
	inputby bpchar(20) NULL,
	updatedate timestamp NULL,
	updateby varchar(20) NULL,
	status bpchar(12) NULL,
	CONSTRAINT po_mst_lampiran_pkey PRIMARY KEY (nodok, nodokref, id)
);