--DROP TABLE IF EXISTS sc_mst."user_sidia";
CREATE TABLE IF NOT EXISTS sc_mst.user_sidia (
    "branch" character(6) NOT NULL,
    "nik" varchar,
    "userid" character(8) NOT NULL,
    "usersname" varchar(15) NOT NULL,
    "userlname" varchar(50),
    "password" character(15) NOT NULL,
    "groupuser" character(8) NOT NULL,
    "level" varchar(1),
    "location" varchar(2),
    "divisi" varchar(2),
    "brand" varchar(2),
    "hold" character(3),
    "lockusr" character(3),
    "login" character(3),
    "expdate" timestamp without time zone,
    "timelock" timestamp without time zone,
    "email" varchar(100),
    "status" character(1),
    "explocking" timestamp without time zone,
    "retrydate" timestamp without time zone,
    "sendstatus" character(1),
    "custcode" character(6),
    "depcode" character(10),
    "supervisorid" character(8),
    "managerid" character(8),
    "inputdate" timestamp without time zone,
    "inputby" varchar(8),
    "updatedate" timestamp without time zone,
    "updateby" varchar(8),
    CONSTRAINT PK_t_user PRIMARY KEY ("branch", "userid")
);