--DROP TABLE IF EXISTS sc_rep."user_sidia";
CREATE TABLE IF NOT EXISTS sc_rep.user_sidia (
    FC_BRANCH character(6) NOT NULL,
    FC_NIK varchar,
    FC_USERID character(8) NOT NULL,
    FC_USERSNAME varchar(15) NOT NULL,
    FC_USERLNAME varchar(50),
    FC_PASSWORD character(15) NOT NULL,
    FC_GROUPUSER character(8) NOT NULL,
    FC_LEVEL varchar(1),
    FC_LOCATION varchar(2),
    FC_DIVISI varchar(2),
    FC_BRAND varchar(2),
    FC_HOLD character(3),
    FC_LOCKUSR character(3),
    FC_LOGIN character(3),
    FD_EXPDATE timestamp without time zone,
    FD_TIMELOCK timestamp without time zone,
    FC_EMAIL varchar(100),
    FC_STATUS character(1),
    fd_explocking timestamp without time zone,
    fd_retrydate timestamp without time zone,
    fc_sendstatus character(1),
    FC_CUSTCODE character(6),
    FC_DEPCODE character(10),
    FC_SUPERVISORID character(8),
    FC_MANAGERID character(8),
    FD_INPUTDATE timestamp without time zone,
    FC_INPUTBY varchar(8),
    FD_UPDATEDATE timestamp without time zone,
    FC_UPDATEBY varchar(8),
    CONSTRAINT PK_t_user PRIMARY KEY (FC_BRANCH, FC_USERID)
);