<?php

/*
 * Bzip2 Properties
 */

define('BZIP2_ARCHIVEFILE_PID', 1);
define('BZIP2_BZIP2DATA_PID', 2);
define('BZIP2_EXTRACTTOPATH_PID', 3);
define('BZIP2_FILEDECOMPRESSEDNAME_PID', 4);
define('BZIP2_FILEINPUTDATA_PID', 5);
define('BZIP2_HASMOREDATA_PID', 6);


/*
 * Bzip2 Enums
 */



/*
 * Bzip2 Methods
 */

define('BZIP2_ABORT_MID', 2);
define('BZIP2_APPEND_MID', 3);
define('BZIP2_COMPRESS_MID', 4);
define('BZIP2_CONFIG_MID', 5);
define('BZIP2_EXTRACT_MID', 6);
define('BZIP2_EXTRACTALL_MID', 7);
define('BZIP2_RESET_MID', 8);
define('BZIP2_SCAN_MID', 9);


/*
 * Bzip2 Events
 */
  
define('BZIP2_BEGINFILE_EID', 1);
define('BZIP2_ENDFILE_EID', 2);
define('BZIP2_ERROR_EID', 3);
define('BZIP2_OVERWRITE_EID', 4);
define('BZIP2_PROGRESS_EID', 5);

/*
 * Gzip Properties
 */

define('GZIP_ARCHIVEFILE_PID', 1);
define('GZIP_COMPRESSIONLEVEL_PID', 2);
define('GZIP_COMPRESSIONMETHOD_PID', 3);
define('GZIP_EXTRACTTOPATH_PID', 4);
define('GZIP_FILECOMPRESSEDDATE_PID', 5);
define('GZIP_FILECOMPRESSEDNAME_PID', 6);
define('GZIP_FILEDECOMPRESSEDNAME_PID', 7);
define('GZIP_FILEDECOMPRESSEDSIZE_PID', 8);
define('GZIP_FILEINPUTDATA_PID', 9);
define('GZIP_GZIPDATA_PID', 10);
define('GZIP_HASMOREDATA_PID', 11);


/*
 * Gzip Enums
 */

define('GZIP_COMPRESSIONMETHOD_DEFLATE', 0);
define('GZIP_COMPRESSIONMETHOD_LZCCOMPRESS', 1);



/*
 * Gzip Methods
 */

define('GZIP_ABORT_MID', 2);
define('GZIP_APPEND_MID', 3);
define('GZIP_COMPRESS_MID', 4);
define('GZIP_CONFIG_MID', 5);
define('GZIP_EXTRACT_MID', 6);
define('GZIP_EXTRACTALL_MID', 7);
define('GZIP_RESET_MID', 8);
define('GZIP_SCAN_MID', 9);


/*
 * Gzip Events
 */
  
define('GZIP_BEGINFILE_EID', 1);
define('GZIP_ENDFILE_EID', 2);
define('GZIP_ERROR_EID', 3);
define('GZIP_OVERWRITE_EID', 4);
define('GZIP_PROGRESS_EID', 5);

/*
 * Jar Properties
 */

define('JAR_ARCHIVEFILE_PID', 1);
define('JAR_COMPRESSIONLEVEL_PID', 2);
define('JAR_EXCLUDEDFILES_PID', 3);
define('JAR_EXTRACTTOPATH_PID', 4);
define('JAR_FILECOUNT_PID', 5);
define('JAR_FILECOMPRESSEDDATE_PID', 6);
define('JAR_FILECOMPRESSEDNAME_PID', 7);
define('JAR_FILECOMPRESSEDSIZE_PID', 8);
define('JAR_FILEDECOMPRESSEDNAME_PID', 9);
define('JAR_FILEDECOMPRESSEDSIZE_PID', 10);
define('JAR_FILEINPUTDATA_PID', 11);
define('JAR_JARDATA_PID', 13);
define('JAR_MANIFESTFILE_PID', 14);
define('JAR_OVERWRITEFILES_PID', 15);
define('JAR_RECURSESUBDIRECTORIES_PID', 16);


/*
 * Jar Enums
 */



/*
 * Jar Methods
 */

define('JAR_ABORT_MID', 2);
define('JAR_APPENDFILES_MID', 3);
define('JAR_COMPRESS_MID', 4);
define('JAR_CONFIG_MID', 5);
define('JAR_DELETE_MID', 6);
define('JAR_EXTRACT_MID', 7);
define('JAR_EXTRACTALL_MID', 8);
define('JAR_INCLUDEFILES_MID', 9);
define('JAR_RESET_MID', 10);
define('JAR_SCAN_MID', 11);


/*
 * Jar Events
 */
  
define('JAR_BEGINFILE_EID', 1);
define('JAR_ENDFILE_EID', 2);
define('JAR_ERROR_EID', 3);
define('JAR_OVERWRITE_EID', 4);
define('JAR_PROGRESS_EID', 5);

/*
 * OfficeDoc Properties
 */

define('OFFICEDOC_CONTENTTYPECOUNT_PID', 1);
define('OFFICEDOC_CONTENTTYPEISOVERRIDE_PID', 2);
define('OFFICEDOC_CONTENTTYPEMEDIATYPE_PID', 3);
define('OFFICEDOC_CONTENTTYPETARGET_PID', 4);
define('OFFICEDOC_NAMESPACECOUNT_PID', 5);
define('OFFICEDOC_NAMESPACEPREFIX_PID', 6);
define('OFFICEDOC_NAMESPACEURI_PID', 7);
define('OFFICEDOC_PACKAGEPATH_PID', 8);
define('OFFICEDOC_PACKAGEPROPERTYCOUNT_PID', 9);
define('OFFICEDOC_PACKAGEPROPERTYDATATYPE_PID', 10);
define('OFFICEDOC_PACKAGEPROPERTYNAME_PID', 11);
define('OFFICEDOC_PACKAGEPROPERTYNAMESPACE_PID', 12);
define('OFFICEDOC_PACKAGEPROPERTYPROPID_PID', 13);
define('OFFICEDOC_PACKAGEPROPERTYPROPSET_PID', 14);
define('OFFICEDOC_PACKAGEPROPERTYVALUE_PID', 15);
define('OFFICEDOC_PARTDATA_PID', 16);
define('OFFICEDOC_PARTNAME_PID', 17);
define('OFFICEDOC_RELATIONSHIPCOUNT_PID', 18);
define('OFFICEDOC_RELATIONSHIPCONTENTTYPE_PID', 19);
define('OFFICEDOC_RELATIONSHIPID_PID', 20);
define('OFFICEDOC_RELATIONSHIPPARTNAME_PID', 21);
define('OFFICEDOC_RELATIONSHIPTYPEURI_PID', 22);
define('OFFICEDOC_VALIDATE_PID', 23);
define('OFFICEDOC_ATTRCOUNT_PID', 24);
define('OFFICEDOC_ATTRNAME_PID', 25);
define('OFFICEDOC_ATTRNAMESPACE_PID', 26);
define('OFFICEDOC_ATTRPREFIX_PID', 27);
define('OFFICEDOC_ATTRVALUE_PID', 28);
define('OFFICEDOC_XCHILDCOUNT_PID', 29);
define('OFFICEDOC_XCHILDNAME_PID', 30);
define('OFFICEDOC_XCHILDNAMESPACE_PID', 31);
define('OFFICEDOC_XCHILDPREFIX_PID', 32);
define('OFFICEDOC_XCHILDXTEXT_PID', 33);
define('OFFICEDOC_XELEMENT_PID', 34);
define('OFFICEDOC_XNAMESPACE_PID', 35);
define('OFFICEDOC_XPARENT_PID', 36);
define('OFFICEDOC_XPATH_PID', 37);
define('OFFICEDOC_XPREFIX_PID', 38);
define('OFFICEDOC_XSUBTREE_PID', 39);
define('OFFICEDOC_XTEXT_PID', 40);


/*
 * OfficeDoc Enums
 */



/*
 * OfficeDoc Methods
 */

define('OFFICEDOC_CLOSE_MID', 2);
define('OFFICEDOC_CONFIG_MID', 3);
define('OFFICEDOC_EXTRACTPART_MID', 4);
define('OFFICEDOC_FINDPARTBYTYPE_MID', 5);
define('OFFICEDOC_GETPROPERTYVALUE_MID', 6);
define('OFFICEDOC_LISTPARTS_MID', 7);
define('OFFICEDOC_OPEN_MID', 8);
define('OFFICEDOC_PARSEPART_MID', 9);
define('OFFICEDOC_READRELATIONSHIPS_MID', 10);
define('OFFICEDOC_REPLACEPART_MID', 11);
define('OFFICEDOC_RESET_MID', 12);
define('OFFICEDOC_RESOLVECONTENTTYPE_MID', 13);


/*
 * OfficeDoc Events
 */
  
define('OFFICEDOC_BEGINFILE_EID', 1);
define('OFFICEDOC_CHARACTERS_EID', 2);
define('OFFICEDOC_COMMENT_EID', 3);
define('OFFICEDOC_ENDELEMENT_EID', 4);
define('OFFICEDOC_ENDFILE_EID', 5);
define('OFFICEDOC_ENDPREFIXMAPPING_EID', 6);
define('OFFICEDOC_ERROR_EID', 7);
define('OFFICEDOC_EVALENTITY_EID', 8);
define('OFFICEDOC_IGNORABLEWHITESPACE_EID', 9);
define('OFFICEDOC_META_EID', 10);
define('OFFICEDOC_OVERWRITE_EID', 11);
define('OFFICEDOC_PI_EID', 12);
define('OFFICEDOC_PROGRESS_EID', 13);
define('OFFICEDOC_SPECIALSECTION_EID', 14);
define('OFFICEDOC_STARTELEMENT_EID', 15);
define('OFFICEDOC_STARTPREFIXMAPPING_EID', 16);

/*
 * SevenZip Properties
 */

define('SEVENZIP_ARCHIVEFILE_PID', 1);
define('SEVENZIP_COMPRESSIONLEVEL_PID', 2);
define('SEVENZIP_COMPRESSIONMETHOD_PID', 3);
define('SEVENZIP_EXCLUDEDFILES_PID', 4);
define('SEVENZIP_EXTRACTTOPATH_PID', 5);
define('SEVENZIP_FILECOUNT_PID', 6);
define('SEVENZIP_FILEATTRIBUTES_PID', 7);
define('SEVENZIP_FILECOMPRESSEDDATE_PID', 8);
define('SEVENZIP_FILECOMPRESSEDNAME_PID', 9);
define('SEVENZIP_FILECOMPRESSEDSIZE_PID', 10);
define('SEVENZIP_FILECOMPRESSIONLEVEL_PID', 11);
define('SEVENZIP_FILECOMPRESSIONMETHOD_PID', 12);
define('SEVENZIP_FILECRC_PID', 13);
define('SEVENZIP_FILEDECOMPRESSEDNAME_PID', 14);
define('SEVENZIP_FILEDECOMPRESSEDSIZE_PID', 15);
define('SEVENZIP_FILEINPUTDATA_PID', 16);
define('SEVENZIP_OVERWRITEFILES_PID', 18);
define('SEVENZIP_PASSWORD_PID', 19);
define('SEVENZIP_RECURSESUBDIRECTORIES_PID', 20);
define('SEVENZIP_SEVENZIPDATA_PID', 21);


/*
 * SevenZip Enums
 */

define('SEVENZIP_COMPRESSIONMETHOD_LZMA', 0);
define('SEVENZIP_COMPRESSIONMETHOD_BZIP_2', 1);
define('SEVENZIP_COMPRESSIONMETHOD_DELTA', 2);
define('SEVENZIP_COMPRESSIONMETHOD_COPY', 3);
define('SEVENZIP_COMPRESSIONMETHOD_DEFLATE', 4);
define('SEVENZIP_COMPRESSIONMETHOD_LZMA_2', 5);

define('SEVENZIP_FILECOMPRESSIONMETHOD_LZMA', 0);
define('SEVENZIP_FILECOMPRESSIONMETHOD_BZIP_2', 1);
define('SEVENZIP_FILECOMPRESSIONMETHOD_DELTA', 2);
define('SEVENZIP_FILECOMPRESSIONMETHOD_COPY', 3);
define('SEVENZIP_FILECOMPRESSIONMETHOD_DEFLATE', 4);
define('SEVENZIP_FILECOMPRESSIONMETHOD_LZMA_2', 5);



/*
 * SevenZip Methods
 */

define('SEVENZIP_ABORT_MID', 2);
define('SEVENZIP_APPENDFILES_MID', 3);
define('SEVENZIP_COMPRESS_MID', 4);
define('SEVENZIP_CONFIG_MID', 5);
define('SEVENZIP_DELETE_MID', 6);
define('SEVENZIP_EXTRACT_MID', 7);
define('SEVENZIP_EXTRACTALL_MID', 8);
define('SEVENZIP_INCLUDEFILES_MID', 9);
define('SEVENZIP_RESET_MID', 10);
define('SEVENZIP_SCAN_MID', 11);
define('SEVENZIP_UPDATE_MID', 14);


/*
 * SevenZip Events
 */
  
define('SEVENZIP_BEGINFILE_EID', 1);
define('SEVENZIP_ENDFILE_EID', 2);
define('SEVENZIP_ERROR_EID', 3);
define('SEVENZIP_OVERWRITE_EID', 4);
define('SEVENZIP_PROGRESS_EID', 5);

/*
 * Tar Properties
 */

define('TAR_ARCHIVEFILE_PID', 1);
define('TAR_EXCLUDEDFILES_PID', 2);
define('TAR_EXTRACTTOPATH_PID', 3);
define('TAR_FILECOUNT_PID', 4);
define('TAR_FILECOMPRESSEDDATE_PID', 5);
define('TAR_FILECOMPRESSEDNAME_PID', 6);
define('TAR_FILECOMPRESSEDSIZE_PID', 7);
define('TAR_FILEDECOMPRESSEDNAME_PID', 8);
define('TAR_FILEDECOMPRESSEDSIZE_PID', 9);
define('TAR_FILEHARDLINKNAME_PID', 10);
define('TAR_FILEINPUTDATA_PID', 11);
define('TAR_FILEPERMISSIONS_PID', 12);
define('TAR_FILESYMLINKNAME_PID', 13);
define('TAR_OVERWRITEFILES_PID', 14);
define('TAR_RECURSESUBDIRECTORIES_PID', 15);
define('TAR_TARDATA_PID', 16);
define('TAR_USEGZIPCOMPRESSION_PID', 17);


/*
 * Tar Enums
 */



/*
 * Tar Methods
 */

define('TAR_ABORT_MID', 2);
define('TAR_APPEND_MID', 3);
define('TAR_COMPRESS_MID', 4);
define('TAR_CONFIG_MID', 5);
define('TAR_DELETE_MID', 6);
define('TAR_EXTRACT_MID', 7);
define('TAR_EXTRACTALL_MID', 8);
define('TAR_INCLUDEFILES_MID', 9);
define('TAR_RESET_MID', 10);
define('TAR_SCAN_MID', 11);


/*
 * Tar Events
 */
  
define('TAR_BEGINFILE_EID', 1);
define('TAR_ENDFILE_EID', 2);
define('TAR_ERROR_EID', 3);
define('TAR_OVERWRITE_EID', 4);
define('TAR_PROGRESS_EID', 5);

/*
 * ZCompress Properties
 */

define('ZCOMPRESS_ARCHIVEFILE_PID', 1);
define('ZCOMPRESS_FILEDECOMPRESSEDNAME_PID', 2);
define('ZCOMPRESS_FILEINPUTDATA_PID', 3);
define('ZCOMPRESS_ZCOMPRESSDATA_PID', 4);


/*
 * ZCompress Enums
 */



/*
 * ZCompress Methods
 */

define('ZCOMPRESS_ABORT_MID', 2);
define('ZCOMPRESS_COMPRESS_MID', 3);
define('ZCOMPRESS_CONFIG_MID', 4);
define('ZCOMPRESS_EXTRACT_MID', 5);
define('ZCOMPRESS_RESET_MID', 6);


/*
 * ZCompress Events
 */
  
define('ZCOMPRESS_BEGINFILE_EID', 1);
define('ZCOMPRESS_ENDFILE_EID', 2);
define('ZCOMPRESS_ERROR_EID', 3);
define('ZCOMPRESS_OVERWRITE_EID', 4);
define('ZCOMPRESS_PROGRESS_EID', 5);

/*
 * Zip Properties
 */

define('ZIP_ARCHIVEFILE_PID', 1);
define('ZIP_COMPRESSIONLEVEL_PID', 2);
define('ZIP_COMPRESSIONMETHOD_PID', 3);
define('ZIP_ENCRYPTIONALGORITHM_PID', 4);
define('ZIP_EXCLUDEDFILES_PID', 5);
define('ZIP_EXTRACTTOPATH_PID', 6);
define('ZIP_FILECOUNT_PID', 7);
define('ZIP_FILEATTRIBUTES_PID', 8);
define('ZIP_FILECOMMENT_PID', 9);
define('ZIP_FILECOMPRESSEDDATE_PID', 10);
define('ZIP_FILECOMPRESSEDNAME_PID', 11);
define('ZIP_FILECOMPRESSEDSIZE_PID', 12);
define('ZIP_FILECOMPRESSIONLEVEL_PID', 13);
define('ZIP_FILECRC_PID', 14);
define('ZIP_FILEDECOMPRESSEDNAME_PID', 15);
define('ZIP_FILEDECOMPRESSEDSIZE_PID', 16);
define('ZIP_FILEENCRYPTIONALGORITHM_PID', 17);
define('ZIP_FILEHASH_PID', 18);
define('ZIP_FILEINPUTDATA_PID', 19);
define('ZIP_FILEPASSWORD_PID', 21);
define('ZIP_FILEPASSWORDREQUIRED_PID', 22);
define('ZIP_OVERWRITEFILES_PID', 23);
define('ZIP_PASSWORD_PID', 24);
define('ZIP_RECURSESUBDIRECTORIES_PID', 25);
define('ZIP_ZIPCOMMENT_PID', 26);
define('ZIP_ZIPDATA_PID', 27);


/*
 * Zip Enums
 */

define('ZIP_COMPRESSIONMETHOD_DEFLATE', 0);
define('ZIP_COMPRESSIONMETHOD_PPMD', 1);
define('ZIP_COMPRESSIONMETHOD_BZIP_2', 2);

define('ZIP_ENCRYPTIONALGORITHM_DEFAULT', 0);
define('ZIP_ENCRYPTIONALGORITHM_AESWEAK', 1);
define('ZIP_ENCRYPTIONALGORITHM_AESSTRONG', 2);
define('ZIP_ENCRYPTIONALGORITHM_AESMAXIMUM', 3);

define('ZIP_FILEENCRYPTIONALGORITHM_DEFAULT', 0);
define('ZIP_FILEENCRYPTIONALGORITHM_AESWEAK', 1);
define('ZIP_FILEENCRYPTIONALGORITHM_AESSTRONG', 2);
define('ZIP_FILEENCRYPTIONALGORITHM_AESMAXIMUM', 3);



/*
 * Zip Methods
 */

define('ZIP_ABORT_MID', 2);
define('ZIP_APPENDFILES_MID', 3);
define('ZIP_COMPRESS_MID', 4);
define('ZIP_CONFIG_MID', 5);
define('ZIP_DELETE_MID', 6);
define('ZIP_EXTRACT_MID', 7);
define('ZIP_EXTRACTALL_MID', 8);
define('ZIP_INCLUDEFILES_MID', 9);
define('ZIP_RESET_MID', 10);
define('ZIP_SCAN_MID', 11);
define('ZIP_UPDATE_MID', 14);


/*
 * Zip Events
 */
  
define('ZIP_BEGINFILE_EID', 1);
define('ZIP_ENDFILE_EID', 2);
define('ZIP_ERROR_EID', 3);
define('ZIP_OVERWRITE_EID', 4);
define('ZIP_PASSWORD_EID', 5);
define('ZIP_PROGRESS_EID', 6);

/*
 * ZipSFX Properties
 */

define('ZIPSFX_ARCHIVEFILE_PID', 1);
define('ZIPSFX_BANNERTEXT_PID', 2);
define('ZIPSFX_CAPTIONTEXT_PID', 3);
define('ZIPSFX_COMPRESSIONLEVEL_PID', 4);
define('ZIPSFX_EXTRACTTOPATH_PID', 5);
define('ZIPSFX_FILETOEXECUTE_PID', 6);
define('ZIPSFX_PASSWORD_PID', 7);
define('ZIPSFX_RECURSESUBDIRECTORIES_PID', 8);
define('ZIPSFX_SOURCEDIRECTORY_PID', 9);


/*
 * ZipSFX Enums
 */



/*
 * ZipSFX Methods
 */

define('ZIPSFX_CONFIG_MID', 2);
define('ZIPSFX_CREATESFX_MID', 3);
define('ZIPSFX_RESET_MID', 4);


/*
 * ZipSFX Events
 */
  
define('ZIPSFX_ERROR_EID', 1);
define('ZIPSFX_PROGRESS_EID', 2);

/*
 * ZipStream Properties
 */

define('ZIPSTREAM_CLOSEBASESTREAM_PID', 1);
define('ZIPSTREAM_COMPRESSIONLEVEL_PID', 2);
define('ZIPSTREAM_INPUTDATA_PID', 3);
define('ZIPSTREAM_OUTPUTDATA_PID', 4);
define('ZIPSTREAM_STREAMFORMAT_PID', 5);


/*
 * ZipStream Enums
 */

define('ZIPSTREAM_STREAMFORMAT_DEFLATE', 0);
define('ZIPSTREAM_STREAMFORMAT_ZLIB', 1);
define('ZIPSTREAM_STREAMFORMAT_GZIP', 2);



/*
 * ZipStream Methods
 */

define('ZIPSTREAM_COMPRESSBLOCK_MID', 2);
define('ZIPSTREAM_COMPRESSDATA_MID', 3);
define('ZIPSTREAM_CONFIG_MID', 4);
define('ZIPSTREAM_DECOMPRESSBLOCK_MID', 5);
define('ZIPSTREAM_DECOMPRESSDATA_MID', 6);
define('ZIPSTREAM_RESET_MID', 9);


/*
 * ZipStream Events
 */
  
define('ZIPSTREAM_COMPRESSEDDATA_EID', 1);
define('ZIPSTREAM_DECOMPRESSEDDATA_EID', 2);
define('ZIPSTREAM_ERROR_EID', 3);



?>
