-- View: sc_his.perawatanspk_view

-- DROP VIEW sc_his.perawatanspk_view;

CREATE OR REPLACE VIEW sc_his.perawatanspk_view AS 
 SELECT COALESCE(x.nodok, ''::bpchar)::text AS nodok,
    COALESCE(x.nodokref, ''::bpchar)::text AS nodokref,
    COALESCE(x.descbarang, ''::bpchar)::text AS descbarang,
    COALESCE(x.kdgroup, ''::bpchar)::text AS kdgroup,
    COALESCE(x.kdsubgroup, ''::bpchar)::text AS kdsubgroup,
    COALESCE(x.stockcode, ''::bpchar)::text AS stockcode,
    COALESCE(x.kdbengkel, ''::bpchar)::text AS kdbengkel,
    COALESCE(x.kdsubbengkel, ''::bpchar)::text AS kdsubbengkel,
    COALESCE(x.upbengkel, ''::bpchar)::text AS upbengkel,
    COALESCE(x.jnsperawatan, ''::bpchar)::text AS jnsperawatan,
    COALESCE(x.jnsperawatanref, ''::bpchar)::text AS jnsperawatanref,
    COALESCE(to_char(x.tgldok, 'dd-mm-yyyy'::text), ''::text) AS tgldok,
    COALESCE(to_char(x.tglawal::timestamp with time zone, 'dd-mm-yyyy'::text), ''::text) AS tglawal,
    COALESCE(to_char(x.tglakhir::timestamp with time zone, 'dd-mm-yyyy'::text), ''::text) AS tglakhir,
    COALESCE(x.keterangan, ''::text) AS keterangan,
    COALESCE(x.status, ''::bpchar)::text AS status,
    COALESCE(to_char(x.inputdate, 'dd-mm-yyyy'::text), ''::text) AS inputdate,
    COALESCE(x.inputby, ''::bpchar)::text AS inputby,
    COALESCE(to_char(x.updatedate, 'dd-mm-yyyy'::text), ''::text) AS updatedate,
    COALESCE(x.updateby, ''::bpchar)::text AS updateby,
    COALESCE(x.nmbarang, ''::bpchar)::text AS nmbarang,
    COALESCE(x.kdgudang, ''::bpchar)::text AS kdgudang,
    COALESCE(x.nmbengkel, ''::character varying)::text AS nmbengkel,
    COALESCE(x.addbengkel, ''::text) AS addbengkel,
    COALESCE(x.city, ''::bpchar)::text AS city,
    COALESCE(x.phone1, ''::bpchar)::text AS phone1,
    COALESCE(x.phone2, ''::bpchar)::text AS phone2,
    COALESCE(x.nopol, ''::bpchar)::text AS nopol,
    COALESCE(x.branch_address, ''::text) AS branch_address,
    COALESCE(x.branch_phone1, ''::text) AS branch_phone1,
    COALESCE(x.branch_phone2, ''::text) AS branch_phone2,
    COALESCE(x.branch_fax, ''::text) AS branch_fax,
    COALESCE(x.nmmohon, ''::bpchar)::text AS nmmohon,
    COALESCE(x.km_awal, 0::numeric)::text AS km_awal,
    COALESCE(x.km_akhir, 0::numeric)::text AS km_akhir,
    COALESCE(x.ttlservis, 0::numeric)::text AS ttlservis,
    COALESCE(x.ttldiskon, 0::numeric)::text AS ttldiskon,
    COALESCE(x.ttldpp, 0::numeric)::text AS ttldpp,
    COALESCE(x.ttlppn, 0::numeric)::text AS ttlppn,
    COALESCE(x.ttlppnbm, 0::numeric)::text AS ttlppnbm,
    COALESCE(x.ttlnetto, 0::numeric)::text AS ttlnetto,
    COALESCE(x.typeservis, ''::bpchar)::text AS typeservis,
    COALESCE(x.nmstatus, ''::bpchar::character varying)::text AS nmstatus,
    COALESCE(x.docdate, ''::bpchar::character varying::text) AS docdate
   FROM ( SELECT a.nodok,
            a.nodokref,
            a.descbarang,
            a.kdgroup,
            a.kdsubgroup,
            a.stockcode,
            a.kdbengkel,
            a.kdsubbengkel,
            a.upbengkel,
            a.jnsperawatan,
            a.jnsperawatanref,
            a.tgldok,
            a.tglawal,
            a.tglakhir,
            a.km_awal,
            a.km_akhir,
            a.ttlservis,
            a.ttldiskon,
            a.ttldpp,
            a.ttlppn,
            a.ttlppnbm,
            a.ttlnetto,
            a.typeservis,
            a.keterangan,
            a.status,
            a.inputdate,
            a.inputby,
            a.updatedate,
            a.updateby,
            a.nodoktmp,
            b.nmbarang,
            b.kdgudang,
            c.nmbengkel,
            c.addbengkel,
            c.city,
            c.phone1,
            c.phone2,
            b.nopol,
            d.address AS branch_address,
            d.phone1 AS branch_phone1,
            d.phone2 AS branch_phone2,
            d.fax AS branch_fax,
            f.nmlengkap AS nmmohon,
            g.uraian AS nmstatus,
            to_char(a.tgldok, 'yyyy-mm-dd'::text) AS docdate
           FROM sc_his.perawatanspk a
             LEFT JOIN sc_mst.mbarang b ON a.stockcode = b.nodok AND a.kdgroup = b.kdgroup AND a.kdsubgroup = b.kdsubgroup
             LEFT JOIN sc_mst.msubbengkel c ON c.kdbengkel = a.kdbengkel AND c.kdsubbengkel = a.kdsubbengkel
             LEFT JOIN sc_mst.branch d ON 'SBYNSA'::bpchar = d.branch
             LEFT JOIN sc_his.perawatanasset e ON a.nodok = e.nodok::bpchar
             LEFT JOIN sc_mst.karyawan f ON f.nik = e.nikmohon
             LEFT JOIN sc_mst.trxtype g ON g.kdtrx = a.status AND g.jenistrx::text = 'PASSET'::text) x
  WHERE x.nodok IS NOT NULL
  ORDER BY (COALESCE(x.nodokref, ''::bpchar)::text) DESC, (COALESCE(x.nodok, ''::bpchar)::text) DESC;

ALTER TABLE sc_his.perawatanspk_view
  OWNER TO postgres;